site_name: HEP ML Living Review
site_url: https://iml-wg.github.io/HEPML-LivingReview/
nav:
  - Home: index.md
  - About: about.md
  - Contribute: contribute.md
  - Resources: resources.md
  - Cite Us: cite.md

repo_url: https://github.com/iml-wg/HEPML-LivingReview/

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.expand
    - toc.follow
    - navigation.top
    # - toc.integrate
    - search.share
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
